name: Release Build

on:
  release:
    types: [published]

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libopencv-dev libtag1-dev libsqlite3-dev

    - name: Build project
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        echo "Building version ${VERSION}"
        make fclean
        make all
        mv tagtool tagtool-${VERSION}
        tar czf tagtool-${VERSION}.tar.gz tagtool-${VERSION}

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.BUILD_TOKEN }}
        files: |
          tagtool-${{ github.event.release.tag_name }}
          tagtool-${{ github.event.release.tag_name }}.tar.gz
