name: Release Build

on:
  release:
    types: [published]

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libopencv-dev libtag1-dev libsqlite3-dev

    - name: Build project
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        echo "Building version ${VERSION}"
        make fclean
        make all
        mv tagtool tagtool-${VERSION}

    - name: Archive build
      env:
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        tar czf tagtool-${VERSION}.tar.gz tagtool-${VERSION}

    - name: Upload binary
      env:
        VERSION: ${{ github.event.release.tag_name }}
      uses: actions/upload-artifact@v3
      with:
        name: tagtool-binary-${{ env.VERSION }}
        path: tagtool-${{ env.VERSION }}

    - name: Upload compressed archive
      env:
        VERSION: ${{ github.event.release.tag_name }}
      uses: actions/upload-artifact@v3
      with:
        name: tagtool-archive-${{ env.VERSION }}
        path: tagtool-${{ env.VERSION }}.tar.gz
